name: Continuous Integration and Deployment

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install Dependencies, Lint, Test, and Build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build

  docker_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Server image
        run: docker build -t jpplay/vox-server .

      - name: Push Server image
        run: docker push jpplay/vox-server:latest

  deploy:
    runs-on: self-hosted
    needs: docker_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create Docker network if not exists
        run: docker network create traefik-net || true

      - name: Deploy server-1
        run: |
          docker rm -f server-1 || true
          docker run -d --name server-1 \
            --cpus="0.15" \
            --network traefik-net \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SALTS="${{ secrets.SALTS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e URL="${{ secrets.URL }}" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.api.rule=Host("${{ secrets.DOMAIN }}") && PathPrefix(`/`)" \
            --label "traefik.http.routers.api.entrypoints=websecure" \
            --label "traefik.http.routers.api.tls.certresolver=myresolver" \
            --label "traefik.http.services.api.loadbalancer.server.port=3000" \
            jpplay/vox-server:latest

      - name: Deploy server-2
        run: |
          docker rm -f server-2 || true
          docker run -d --name server-2 \
            --cpus="0.15" \
            --network traefik-net \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SALTS="${{ secrets.SALTS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e URL="${{ secrets.URL }}" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.api.rule=Host("${{ secrets.DOMAIN }}") && PathPrefix(`/`)" \
            --label "traefik.http.routers.api.entrypoints=websecure" \
            --label "traefik.http.routers.api.tls.certresolver=myresolver" \
            --label "traefik.http.services.api.loadbalancer.server.port=3000" \
            jpplay/vox-server:latest

      - name: Deploy server-3
        run: |
          docker rm -f server-3 || true
          docker run -d --name server-3 \
            --cpus="0.15" \
            --network traefik-net \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SALTS="${{ secrets.SALTS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e URL="${{ secrets.URL }}" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.api.rule=Host("${{ secrets.DOMAIN }}") && PathPrefix(`/`)" \
            --label "traefik.http.routers.api.entrypoints=websecure" \
            --label "traefik.http.routers.api.tls.certresolver=myresolver" \
            --label "traefik.http.services.api.loadbalancer.server.port=3000" \
            jpplay/vox-server:latest

      - name: Deploy server-4
        run: |
          docker rm -f server-4 || true
          docker run -d --name server-4 \
            --cpus="0.15" \
            --network traefik-net \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SALTS="${{ secrets.SALTS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e URL="${{ secrets.URL }}" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.api.rule=Host("${{ secrets.DOMAIN }}") && PathPrefix(`/`)" \
            --label "traefik.http.routers.api.entrypoints=websecure" \
            --label "traefik.http.routers.api.tls.certresolver=myresolver" \
            --label "traefik.http.services.api.loadbalancer.server.port=3000" \
            jpplay/vox-server:latest

      - name: Deploy server-5 (dedicado /socket.io e /user)
        run: |
          docker rm -f server-5 || true
          docker run -d --name server-5 \
            --cpus="0.15" \
            --network traefik-net \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e EMAIL_ADDRESS="${{ secrets.EMAIL_ADDRESS }}" \
            -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SALTS="${{ secrets.SALTS }}" \
            -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
            -e URL="${{ secrets.URL }}" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.realtime.rule=Host("${{ secrets.DOMAIN }}") && (PathPrefix(`/socket.io/`) || PathPrefix(`/user`))" \
            --label "traefik.http.routers.realtime.entrypoints=websecure" \
            --label "traefik.http.routers.realtime.tls.certresolver=myresolver" \
            --label "traefik.http.services.realtime.loadbalancer.server.port=3000" \
            jpplay/vox-server:latest

      - name: Deploy reverse proxy
        run: |
          docker rm -f traefik || true
          docker run -d --name traefik -p 80:80 -p 443:443 -p 8080:8080 \
              -v "${{ github.workspace }}/traefik.yml:/etc/traefik/traefik.yml:ro" \
              -v /etc/traefik/letsencrypt:/letsencrypt \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -v /etc/traefik/config:/etc/traefik/config \
              traefik:v3.2